"""add nrb pipeline run tables

Revision ID: 1fb5a0d183d6
Revises: 8f2d1c05a7b4
Create Date: 2026-08-17

Phase 7 step 4 — the shared pipeline runner (`docs/nrb-integration.md` §23).
Two new tables, no change to any existing one.

WHY A NEW TABLE AND NOT AN EXISTING ONE
    `nrb_sync_runs` and `nrb_fetch_runs` each record ONE stage and are the
    detailed truth for it. Neither can answer "is an NRB update running", "who
    asked for it", "which stage is it on" or "did the whole thing finish",
    because a whole update spans four stages plus asynchronous RAG jobs owned by
    a separate process. `nrb_pipeline_runs` is that orchestration record and
    nothing more: per-item detail stays in the stage tables, `documents`,
    `ingest_jobs` and the recovery cache.

    `nrb_pipeline_run_jobs` is the explicit run -> job relation. It is a
    separate table rather than a column on `ingest_jobs` because that table is
    shared with ordinary department uploads and has no business knowing NRB
    exists — and because a `--retry-failed` job belongs to the run that retried
    it, not to the run that first created the document. Reconstructing the
    relation from timestamps was rejected: the scratch database alone holds 190
    unrelated `ri*` documents with stale jobs, which a time-window query would
    adopt.

LINEAGE
    `down_revision` is `8f2d1c05a7b4`, this branch's actual head. The deferred
    `feat/rag-source-citations` lineage (`d4a91f2c7b3e`) is untouched and
    nothing is stamped; the eventual merge revision is still required and still
    not solved here. Applied against `local_ai_gateway_p4` only.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fb5a0d183d6'
down_revision: Union[str, None] = '8f2d1c05a7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nrb_pipeline_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('counters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(finished_at IS NULL) = (status IN ('running', 'awaiting_jobs'))", name='ck_nrb_pipeline_runs_finished'),
    sa.CheckConstraint("stage IN ('sync', 'fetch', 'extract', 'rag', 'waiting', 'done')", name='ck_nrb_pipeline_runs_stage'),
    sa.CheckConstraint("status IN ('running', 'awaiting_jobs', 'succeeded', 'partial', 'failed')", name='ck_nrb_pipeline_runs_status'),
    sa.CheckConstraint("trigger IN ('cli', 'api', 'schedule')", name='ck_nrb_pipeline_runs_trigger'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nrb_pipeline_runs_created', 'nrb_pipeline_runs', ['created_at'], unique=False)
    op.create_index('ix_nrb_pipeline_runs_status', 'nrb_pipeline_runs', ['status'], unique=False)
    op.create_table('nrb_pipeline_run_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingest_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['nrb_pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nrb_pipeline_run_jobs_job', 'nrb_pipeline_run_jobs', ['job_id'], unique=False)
    op.create_index('ux_nrb_pipeline_run_jobs', 'nrb_pipeline_run_jobs', ['run_id', 'job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_nrb_pipeline_run_jobs', table_name='nrb_pipeline_run_jobs')
    op.drop_index('ix_nrb_pipeline_run_jobs_job', table_name='nrb_pipeline_run_jobs')
    op.drop_table('nrb_pipeline_run_jobs')
    op.drop_index('ix_nrb_pipeline_runs_status', table_name='nrb_pipeline_runs')
    op.drop_index('ix_nrb_pipeline_runs_created', table_name='nrb_pipeline_runs')
    op.drop_table('nrb_pipeline_runs')
    # ### end Alembic commands ###
