"""add nrb recovery cache tables

Revision ID: 714264eba2fd
Revises: b1bea6ac36c5
Create Date: 2026-08-17 09:46:00.167448

Phase 7 step 2 — the versioned recovery cache (`docs/nrb-integration.md` §21).
Two tables, no change to any existing one.

LINEAGE
    `down_revision` is `b1bea6ac36c5`, this branch's ACTUAL head. It is
    deliberately not chained onto `d4a91f2c7b3e`, which exists only on the
    deferred `feat/rag-source-citations` branch: that branch is not abandoned
    and its lineage is reconciled before NRB merges, not before NRB is built.

    Consequence, stated here rather than discovered later: when the two branches
    do meet, Alembic will have two heads and **a merge revision will be needed**.
    Nothing in this file tries to solve that, and nothing here should be
    `alembic stamp`ed to make the dev database agree — see CLAUDE.md.

    Applied and verified against the scratch database `local_ai_gateway_p4`
    only.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '714264eba2fd'
down_revision: Union[str, None] = 'b1bea6ac36c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nrb_recoveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('base_version', sa.String(length=255), nullable=False),
    sa.Column('family', sa.String(length=16), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('plan_reason', sa.String(length=64), nullable=False),
    sa.Column('gate_ratio', sa.Float(), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('unit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("plan IN ('keep_native', 'convert_units', 'route_pages', 'no_recovery')", name='ck_nrb_recoveries_plan'),
    sa.CheckConstraint('gate_ratio IS NULL OR (gate_ratio >= 0 AND gate_ratio <= 1)', name='ck_nrb_recoveries_gate_ratio'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_nrb_recoveries_content_version', 'nrb_recoveries', ['content_sha256', 'base_version'], unique=True)
    op.create_table('nrb_recovery_units',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recovery_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('route', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=255), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("route IN ('native', 'legacy_conversion', 'ocr')", name='ck_nrb_recovery_units_route'),
    sa.CheckConstraint('error IS NULL OR ok = false', name='ck_nrb_recovery_units_error'),
    sa.CheckConstraint('unit_number >= 1', name='ck_nrb_recovery_units_number'),
    sa.ForeignKeyConstraint(['recovery_id'], ['nrb_recoveries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nrb_recovery_units_route', 'nrb_recovery_units', ['route'], unique=False)
    op.create_index('ux_nrb_recovery_units_recovery_number', 'nrb_recovery_units', ['recovery_id', 'unit_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_nrb_recovery_units_recovery_number', table_name='nrb_recovery_units')
    op.drop_index('ix_nrb_recovery_units_route', table_name='nrb_recovery_units')
    op.drop_table('nrb_recovery_units')
    op.drop_index('ux_nrb_recoveries_content_version', table_name='nrb_recoveries')
    op.drop_table('nrb_recoveries')
    # ### end Alembic commands ###
