"""add file source + message attachments

Revision ID: 7c1e36a23883
Revises: b17ee43dcc29
Create Date: 2026-08-05 14:18:00.908672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c1e36a23883'
down_revision: Union[str, None] = 'b17ee43dcc29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('generated_files', sa.Column('source', sa.String(length=16), server_default='generated', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_files', 'source')
    op.drop_column('chat_messages', 'attachments')
    # ### end Alembic commands ###
