"""add nrb catalog tables

Revision ID: 9a1c4f7b2e05
Revises: c33c0fd56028
Create Date: 2026-08-14 09:40:00.000000

The persistent NRB catalog (Phase 4): logical sources, physical files, the
many-to-many between them, and a log of what each reconciliation did.

Hand-written rather than autogenerated for one reason: two of the four unique
indexes are PARTIAL, and the predicates are load-bearing rather than incidental.
`ux_nrb_sources_post` covers only rows that HAVE a WordPress post id, because a
sitemap-only source has none and a plain UNIQUE(wp_post_type, wp_post_id) would
let exactly one NULL-id row exist in the whole table.

Table order is FK order: nrb_sync_runs first (both catalog tables point at it),
then nrb_files, then nrb_sources, then the join table.

Nothing here touches the pgvector/RAG schema.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9a1c4f7b2e05'
down_revision: Union[str, None] = 'c33c0fd56028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ------------------------------------------------------------------ runs #
    op.create_table(
        "nrb_sync_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="running", nullable=False),
        sa.Column("discovery_complete", sa.Boolean(),
                  server_default=sa.text("false"), nullable=False),
        sa.Column("deactivation_applied", sa.Boolean(),
                  server_default=sa.text("false"), nullable=False),
        sa.Column("dry_run", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sitemaps_seen", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sources_seen", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sources_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sources_updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sources_unchanged", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sources_deactivated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sources_reactivated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sitemap_only_sources", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("files_seen", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("files_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("files_updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("files_unchanged", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("blocked_files", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("relationships_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("relationships_removed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("relationships_updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("warning_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("notes", postgresql.JSONB(astext_type=sa.Text()),
                  server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'partial', 'failed')",
            name="ck_nrb_sync_runs_status",
        ),
        # A run that did not see the whole corpus may not have deactivated
        # anything. Enforced here as well as in the service, so the impossible
        # combination cannot be recorded even by a future caller.
        sa.CheckConstraint(
            "NOT (deactivation_applied AND NOT discovery_complete)",
            name="ck_nrb_sync_runs_deactivation_needs_complete",
        ),
    )

    # ----------------------------------------------------------------- files #
    op.create_table(
        "nrb_files",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        # Percent-decoded identity (`attachments.comparison_key`). The same file
        # spelled with literal Devanagari and with percent-escapes collapses here.
        sa.Column("comparison_key", sa.String(length=2048), nullable=False),
        # NRB's own spelling — what a downloader must request.
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=True),
        sa.Column("reported_mime_type", sa.String(length=128), nullable=True),
        sa.Column("extension", sa.String(length=16), nullable=True),
        sa.Column("resource_type", sa.String(length=16), nullable=False),
        sa.Column("type_source", sa.String(length=16), nullable=False),
        sa.Column("reported_bytes", sa.BigInteger(), nullable=True),
        sa.Column("wp_attachment_id", sa.Integer(), nullable=True),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("fetch_status", sa.String(length=16),
                  server_default="pending", nullable=False),
        sa.Column("blocked_reason", sa.Text(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("last_sync_run_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["last_sync_run_id"], ["nrb_sync_runs.id"],
                                ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        # Phase 4 downloads nothing, so there are exactly two states. Phase 5
        # adds its own and must edit this CHECK.
        sa.CheckConstraint(
            "fetch_status IN ('pending', 'blocked_host')",
            name="ck_nrb_files_fetch_status",
        ),
        # "Blocked with no reason" would be indistinguishable from a bug in the
        # host guard.
        sa.CheckConstraint(
            "(fetch_status = 'blocked_host') = (blocked_reason IS NOT NULL)",
            name="ck_nrb_files_blocked_reason",
        ),
    )
    op.create_index("ux_nrb_files_comparison_key", "nrb_files",
                    ["comparison_key"], unique=True)
    # Phase 5's work queue is "every file not yet fetched". `host` is deliberately
    # NOT indexed: the live corpus has two distinct values (18,295 / 3).
    op.create_index("ix_nrb_files_fetch_status", "nrb_files", ["fetch_status"])

    # --------------------------------------------------------------- sources #
    op.create_table(
        "nrb_sources",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("wp_post_id", sa.Integer(), nullable=True),
        sa.Column("wp_post_type", sa.String(length=64), nullable=True),
        sa.Column("page_url", sa.String(length=2048), nullable=False),
        # Comparison identity: `comparison_key` plus a trailing-slash strip. The
        # sitemap percent-encodes Devanagari slugs while REST returns them
        # literally, so raw-string matching would report every REST document as
        # absent from the sitemap and insert it again as a sitemap-only row.
        sa.Column("url_key", sa.String(length=2048), nullable=False),
        sa.Column("canonical_url", sa.String(length=2048), nullable=True),
        sa.Column("slug", sa.String(length=512), nullable=True),
        # Text, not String(n): Devanagari regulatory titles must not be truncated.
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sitemap_lastmod", sa.DateTime(timezone=True), nullable=True),
        # NRB's department/office code. `owner`, not `department`: in this codebase
        # `department` is the RAG permission boundary.
        sa.Column("owner", sa.String(length=32), nullable=True),
        sa.Column("page_kind", sa.String(length=32), nullable=True),
        # NULL is a legitimate answer for ~28% of the corpus (WordPress's
        # `upload-files` catch-all from NRB's 2019 CMS migration). Never guessed.
        sa.Column("document_type", sa.String(length=32), nullable=True),
        sa.Column("classification_source", sa.Text(), nullable=True),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()),
                  server_default=sa.text("'[]'::jsonb"), nullable=False),
        sa.Column("raw_taxonomy", postgresql.JSONB(astext_type=sa.Text()),
                  server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()),
                  server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("metadata_status", sa.String(length=16),
                  server_default="rest", nullable=False),
        sa.Column("metadata_hash", sa.String(length=64), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("last_sync_run_id", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["last_sync_run_id"], ["nrb_sync_runs.id"],
                                ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "metadata_status IN ('rest', 'sitemap_only')",
            name="ck_nrb_sources_metadata_status",
        ),
        # A post id with no type could not participate in the partial unique
        # index below, so it would silently escape identity altogether.
        sa.CheckConstraint(
            "(wp_post_id IS NULL) OR (wp_post_type IS NOT NULL)",
            name="ck_nrb_sources_post_identity",
        ),
    )
    # Primary identity. PARTIAL: sitemap-only rows have no post id, and a plain
    # UNIQUE would permit exactly one of them.
    op.create_index(
        "ux_nrb_sources_post", "nrb_sources", ["wp_post_type", "wp_post_id"],
        unique=True, postgresql_where=sa.text("wp_post_id IS NOT NULL"),
    )
    # Fallback identity, and the join key against the sitemap inventory.
    op.create_index("ux_nrb_sources_url_key", "nrb_sources", ["url_key"], unique=True)
    # Phase 5 selects its corpus by type (the regulatory core is ~1,800 of
    # 18,370). Dates and `is_active` are deliberately not indexed: an 18k-row scan
    # is sub-millisecond and the sync never queries by them.
    op.create_index("ix_nrb_sources_document_type", "nrb_sources", ["document_type"])
    op.create_index("ix_nrb_sources_owner", "nrb_sources", ["owner"])

    # ---------------------------------------------------------- source_files #
    op.create_table(
        "nrb_source_files",
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("file_id", sa.BigInteger(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("relationship_type", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        # Asymmetric on purpose: deleting a source takes its links with it, but a
        # file cannot be deleted while any source still references it.
        sa.ForeignKeyConstraint(["source_id"], ["nrb_sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["file_id"], ["nrb_files.id"], ondelete="RESTRICT"),
        # The composite PK IS the required UNIQUE(source_id, file_id): a duplicate
        # relationship is impossible rather than merely avoided.
        sa.PrimaryKeyConstraint("source_id", "file_id"),
        sa.CheckConstraint(
            "relationship_type IN ('primary', 'secondary', 'acf', 'body_link')",
            name="ck_nrb_source_files_relationship_type",
        ),
    )
    # The PK covers source -> files; this covers files -> sources, which is what
    # makes it safe to keep a file whose last relationship was just removed.
    op.create_index("ix_nrb_source_files_file", "nrb_source_files", ["file_id"])


def downgrade() -> None:
    op.drop_index("ix_nrb_source_files_file", table_name="nrb_source_files")
    op.drop_table("nrb_source_files")
    op.drop_index("ix_nrb_sources_owner", table_name="nrb_sources")
    op.drop_index("ix_nrb_sources_document_type", table_name="nrb_sources")
    op.drop_index("ux_nrb_sources_url_key", table_name="nrb_sources")
    op.drop_index("ux_nrb_sources_post", table_name="nrb_sources")
    op.drop_table("nrb_sources")
    op.drop_index("ix_nrb_files_fetch_status", table_name="nrb_files")
    op.drop_index("ux_nrb_files_comparison_key", table_name="nrb_files")
    op.drop_table("nrb_files")
    op.drop_table("nrb_sync_runs")
