"""add nrb extractions table

Revision ID: b1bea6ac36c5
Revises: 2b7f5c9d1a34
Create Date: 2026-08-15 08:25:24.022883

Phase 6A: native extraction results for fetched NRB blobs.

ONE table, and it is keyed on the CONTENT HASH rather than on `nrb_files.id`.
Storage is content-addressed and a blob is shared across file rows (Phase 3
measured 42 duplicate attachment references; Phase 5 found byte-identical
duplicates inside the first 25 files), so a per-file-row table would parse the
same bytes twice and store two answers to one question. There is deliberately no
foreign key to `nrb_files`: a file row being re-fetched must not orphan a valid
extraction OF THE SAME BYTES.

Every column is a function of the bytes alone. Nothing here derives from a source
title, URL or document type — a blob referenced by one Devanagari-titled and one
English-titled source would otherwise persist a different verdict depending on
which source the pass reached first. Those joins happen at read time in
`app/nrb/profile.py`.

Five CHECKs, each preventing a state that would be silently wrong rather than
loudly broken:

  * `status` / `reason` — closed vocabularies. A typo'd value would match no
    predicate and no query, so the row would read as evaluated while meaning
    nothing (the `ck_ingest_jobs_status` lesson).
  * `error` — a `failed` row that cannot say why is indistinguishable from a bug,
    and a successful row must not carry one.
  * `legacy_counts` — the legacy-line numerator and denominator travel together,
    and the numerator can never exceed the denominator.
  * `preview_is_bounded` — the guarantee this table never becomes a document
    store. NO extracted text is persisted; Phase 7 re-parses with Docling for
    chunking anyway, and a text column that could hold a whole document is
    something a later phase would eventually embed by accident.

Verified against the Phase 4/5 scratch database `local_ai_gateway_p4` ONLY —
upgrade, downgrade, re-upgrade and `alembic check`. The real dev database is
stamped at `d4a91f2c7b3e` from the deferred `feat/rag-source-citations` branch
and is deliberately not migrated from here (docs/nrb-integration.md §9.10).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1bea6ac36c5'
down_revision: Union[str, None] = '2b7f5c9d1a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nrb_extractions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('extractor_version', sa.String(length=32), nullable=False),
    sa.Column('parser', sa.String(length=32), nullable=False),
    sa.Column('media_family', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('pages_with_text', sa.Integer(), nullable=True),
    sa.Column('text_page_coverage', sa.Float(), nullable=True),
    sa.Column('median_chars_per_page', sa.Float(), nullable=True),
    sa.Column('median_chars_per_text_page', sa.Float(), nullable=True),
    sa.Column('char_count', sa.BigInteger(), nullable=False),
    sa.Column('devanagari_ratio', sa.Float(), nullable=True),
    sa.Column('legacy_line_ratio', sa.Float(), nullable=True),
    sa.Column('legacy_lines', sa.Integer(), nullable=True),
    sa.Column('judged_lines', sa.Integer(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'failed') = (error IS NOT NULL)", name='ck_nrb_extractions_error'),
    sa.CheckConstraint("reason IN ('clean', 'legacy_font_suspected', 'partial_text_coverage', 'replacement_characters', 'control_characters', 'low_printable_ratio', 'empty_spreadsheet', 'no_text_layer', 'sparse_text_layer', 'image_file', 'no_native_parser', 'parser_error')", name='ck_nrb_extractions_reason'),
    sa.CheckConstraint("status IN ('extracted', 'suspicious', 'needs_ocr', 'unsupported', 'failed')", name='ck_nrb_extractions_status'),
    sa.CheckConstraint('(legacy_lines IS NULL) = (judged_lines IS NULL) AND (legacy_lines IS NULL OR legacy_lines <= judged_lines)', name='ck_nrb_extractions_legacy_counts'),
    sa.CheckConstraint('preview IS NULL OR char_length(preview) <= 300', name='ck_nrb_extractions_preview_is_bounded'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nrb_extractions_status', 'nrb_extractions', ['status'], unique=False)
    op.create_index('ux_nrb_extractions_content_version', 'nrb_extractions', ['content_sha256', 'extractor_version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_nrb_extractions_content_version', table_name='nrb_extractions')
    op.drop_index('ix_nrb_extractions_status', table_name='nrb_extractions')
    op.drop_table('nrb_extractions')
    # ### end Alembic commands ###
