"""add rag tables

Revision ID: c33c0fd56028
Revises: 7c1e36a23883
Create Date: 2026-08-09 07:01:04.480092

Hand-written rather than autogenerated, for two reasons:
  - CREATE EXTENSION vector must run before any vector(1536) column exists.
  - Neither the HNSW operator class nor its WITH (m, ef_construction) build
    options survive autogeneration, so those two indexes are raw SQL. They are
    also excluded from autogenerate comparison in alembic/env.py.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c33c0fd56028'
down_revision: Union[str, None] = '7c1e36a23883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Must precede any vector(1536) column.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )

    op.create_table(
        "user_departments",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("granted_by", sa.Integer(), nullable=True),
        sa.Column("granted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["granted_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("user_id", "department_id"),
    )

    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("file_type", sa.String(length=16), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        # Relative key under RAG_DOCS_DIR, never an absolute host path.
        sa.Column("storage_key", sa.String(length=1024), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("embed_model", sa.String(length=128), nullable=True),
        sa.Column("embed_dim", sa.Integer(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()),
                  server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        # FK target for the chunk composite FK below.
        sa.UniqueConstraint("id", "department_id", name="uq_documents_id_department"),
        # Closed vocabularies: ux_documents_active_content's predicate keys off
        # the exact string 'archived'.
        sa.CheckConstraint(
            "status IN ('pending', 'ready', 'failed', 'archived')",
            name="ck_documents_status",
        ),
        sa.CheckConstraint(
            "source IN ('upload', 'manual')", name="ck_documents_source"
        ),
    )
    op.create_index("ix_documents_department", "documents", ["department_id"])
    op.create_index("ix_documents_status", "documents", ["status"])
    # Partial: archived rows are retained for audit but must not block re-upload.
    op.create_index(
        "ux_documents_active_content", "documents", ["department_id", "content_hash"],
        unique=True, postgresql_where=sa.text("status <> 'archived'"),
    )

    op.create_table(
        "document_chunks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.String(length=32), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(1536), nullable=False),
        sa.Column("tsv", postgresql.TSVECTOR(),
                  sa.Computed("to_tsvector('english', content)", persisted=True), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("section", sa.String(length=512), nullable=True),
        sa.Column("element_type", sa.String(length=32), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()),
                  server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_document_chunks_doc_index"),
        # The invariant: a chunk's department is provably its document's.
        sa.ForeignKeyConstraint(
            ["document_id", "department_id"],
            ["documents.id", "documents.department_id"],
            ondelete="CASCADE",
            name="fk_document_chunks_document_department",
        ),
    )
    op.create_index("ix_chunks_department", "document_chunks", ["department_id"])
    # Raw SQL: the operator class and the WITH options do not survive autogenerate.
    op.execute(
        "CREATE INDEX ix_chunks_embedding ON document_chunks "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )
    op.execute("CREATE INDEX ix_chunks_tsv ON document_chunks USING gin (tsv)")

    op.create_table(
        "ingest_jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("document_id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="queued", nullable=False),
        sa.Column("chunks_total", sa.Integer(), nullable=True),
        sa.Column("chunks_done", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        # Load-bearing: a typo'd status would match neither the partial index
        # predicate nor the worker's claim query, bypassing both.
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed')",
            name="ck_ingest_jobs_status",
        ),
    )
    op.create_index("ix_ingest_jobs_status", "ingest_jobs", ["status", "created_at"])
    # One ACTIVE job per document (SKIP LOCKED only guards a single row).
    op.create_index(
        "ux_ingest_jobs_active_document", "ingest_jobs", ["document_id"],
        unique=True, postgresql_where=sa.text("status IN ('queued', 'running')"),
    )

    # Bind a conversation to the tab it was opened in. NULL = general chat.
    op.add_column("chat_sessions", sa.Column("department_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_chat_sessions_department", "chat_sessions", "departments",
        ["department_id"], ["id"], ondelete="RESTRICT",
    )


def downgrade() -> None:
    op.drop_constraint("fk_chat_sessions_department", "chat_sessions", type_="foreignkey")
    op.drop_column("chat_sessions", "department_id")
    op.drop_index("ux_ingest_jobs_active_document", table_name="ingest_jobs")
    op.drop_index("ix_ingest_jobs_status", table_name="ingest_jobs")
    op.drop_table("ingest_jobs")
    op.execute("DROP INDEX IF EXISTS ix_chunks_tsv")
    op.execute("DROP INDEX IF EXISTS ix_chunks_embedding")
    op.drop_index("ix_chunks_department", table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index("ux_documents_active_content", table_name="documents")
    op.drop_index("ix_documents_status", table_name="documents")
    op.drop_index("ix_documents_department", table_name="documents")
    op.drop_table("documents")
    op.drop_table("user_departments")
    op.drop_table("departments")
    # The extension is left installed: other databases/objects may rely on it.
