"""add chat_messages.sources

Structured, document-level provenance for a RAG answer, so the frontend can
render clickable "Sources" and a reloaded thread shows the same links the live
turn did.

Nullable with no default: NULL means "this turn searched no corpus", which is a
different statement from "searched and found nothing" (that is an empty list).
Backfilling `[]` would erase the distinction for every pre-existing row.

Hand-written rather than autogenerated: `alembic/env.py` excludes the RAG HNSW
and GIN indexes from comparison, and an autogenerate run here would still churn
unrelated diffs. One column does not need the machinery.

Revision ID: d4a91f2c7b3e
Revises: f4c1a90b7d62
Create Date: 2026-08-09

Rebased 2026-08-19 per docs/nrb-integration.md §27.4. This revision was authored
as a SIBLING of the NRB chain (both off c33c0fd56028) while citations was
deferred. Un-deferring it makes it a descendant instead, so the graph stays one
linear head and no merge revision is ever needed. The revision ID is deliberately
unchanged — a database is stamped at it, and §27.4 assigns that database's
reconciliation to this work rather than to NRB's.

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d4a91f2c7b3e"
down_revision: Union[str, None] = "f4c1a90b7d62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "chat_messages",
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("chat_messages", "sources")
